# Site settings
baseurl = "https://bobconf.com/"
languageCode = "en-gb"
title = "Bobconf: Battle of the Beards"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-89910766-1"

[params]
  name = "BoB conf"
  description = " A day of full-stack tech talks - raising funds to combat male suicide"

  email = "steph@itsalocke.com"

  # Link custom assets relative to /static
  custom_css = ["css/beardy.css"]
  custom_js  = []
  favicon = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # Navigation
  [params.navigation]
    brand = "BoB conf"
    services = "About"
    portfolio = "Last year's talks"
	eventbrite = "Register"
    schedule = "Last year's schedule"
    team = "People"
    contact = "Get involved"


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = 'Help fight male suicide at the Battle of the Beards'
    subtitle = "Last year we raised £1,000 and we've got another event coming soon!"
    buttonText = "Tell me more"
  [params.eventbrite]
    enable = true
    title = "Register"


  # Services section
  [params.services]
    enable = true
    title = "About"

    subtitle = "**If you care about IT stuff and people too then get yourself to BoB conf**<br><br>We're gonna have a fantastic day learning about different IT topics, meeting nifty folks, and letting off a bit of steam. We're gonna be sociable (yes, I know we’re IT people) and have positive human interactions that make a difference in each other’s lives.<br><br>Battle of the Beards started out as a fun user group event, where bristling techies would square off in our very own arena. Our Beardy Battlers would give presentations and winners would be decided based on the quality of their beards and their talks. The crowd went wild (and wanted more)! <br><br>Where our first events had a mere 3 contenders, in 2017 we had a full day event and raised £1,000 for [Campaign Against Living Miserably (CALM)](https://www.thecalmzone.net/). Supporting CALM means they can provide vital counselling services and save lives.<br><br>In our male dominated industry, we’re likely to be disproportionately affected by suicide. It was the cause of a quarter of all deaths of 20 - 34 year old males in [2014](http://webarchive.nationalarchives.gov.uk/20160105160709/http://www.ons.gov.uk/ons/rel/vsob1/mortality-statistics--deaths-registered-in-england-and-wales--series-dr-/2014/sty-what-do-we-die-from.html). That's a sad and uncomfortable fact. <br><br>We need to take care of ourselves and each other. <br><br>So let’s have some fun for a good cause!"
    ps = ""
    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-clock-o"
      title = "Details"
      description = "TBC"
	  
    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Breadth is the new black"
      description = "Our wonderful speakers are giving [talks](#portfolio) that everyone can get something out of. Learn about infrastructure, software craftmanship, data visualisation, and front-end coding. Come learn a little about a lot!"

    [[params.services.row.list]]
      icon = "fa-heart"
      title = "Do something good"
      description = "Attend to have a good time and raise funds that will support [CALM](https://www.thecalmzone.net/), a male suicide awareness and prevention charity. Your support will help them offer vital emergency counselling services."


   
   [[params.services.row.list]]
      icon = "fa-question"
      title = "Why Battle of the Beards?"
      description = "Steph, our lead organiser, has been organising events for more than 5 years. She wanted to spice things up a bit and keep her user group events interesting. Battle of the Beards was one of the crazy ideas she came up with and launched. Read more in our [History](AboutEvents)."
	  
   [[params.services.row.list]]
      icon = "fa-question"
      title = "Do I need a beard?"
      description = "**Nope!** Speakers can sport a beard, real or artificial, for the funsies, but attendees need only bring themselves along. We're committed to a fun event, not a bearded one. We want to ensure everyone has a good time and there will be a [Code of Conduct](codeofconduct) in place."
	
# Portfolio section
  [params.schedule]
    enable = true
    title = "Schedule"

  # Portfolio section
  [params.portfolio]
    enable = true
    title = "Talks"
    subtitle = "Check out the talks from awesome people"

    [params.portfolio.modal]
      client = "Title"
      buttonText = "Back"

    # About section
  [params.about]
    enable = true
    title = "The plan"
    subtitle = "Here's what's happening"
    endpoint = "Join us"
	endpointurl ="https://battleofthebeards.eventbrite.co.uk"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
      [[params.about.events]]
      img = "2.jpg"
      date = " 15 October  2018"
      title = "Registration opens"
      description = "Register for BoB conf and make a difference! It's £150 to cover the costs for the event. You can also add a donation for [Campaign Against Living Miserably (CALM)](https://www.thecalmzone.net/)."
      
    [[params.about.events]]
      img = "1.jpg"
      date = "1 November 2018"
      title = "Open for talks"
      description = "Submit your talks today. Donate your time to educate people and help raise awareness of male suicide."


    [[params.about.events]]
      img = "3.jpg"
      date = "1 February 2019"
      title = "Talks selected"
      description = "We will select talks and announce the agenda"

    [[params.about.events]]
      img = "4.jpg"
      date = "14 March 2019"
      title = "BOB CONF"
      description = "The conference is here!"


  # Team section
  [params.team]
    enable = true
    title = "Key people"
    subtitle = "People contributing to make BoB Conf, and our fight against male suicide, a success!"
    description = "You can get involved too, whether it's by attending, contributing your skills, helping out on the day, or just plain old donating to CALM. You can help us prevent the single biggest killer of young and middle-aged men."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    [[params.team.members]]
      img = "BeardedSteph.png"
      name = "Steph Locke"
      position = "Organiser"
      social = [
        ["fa-twitter", "//twitter.com/stefflocke"],
        ["fa-github", "//github.com/stephlocke"],
        ["fa-home", "//itsalocke.com"]
      ]

    [[params.team.members]]
      img = "DaveParr.jpg"
      name = "David Parr"
      position = "Donating time, Speaking"
      social = [
        ["fa-twitter", "//twitter.com/biomicron"],
        ["fa-github", "//github.com/davergp"],
        ["fa-home", "//davergp.github.io"]
      ]

    [[params.team.members]]
      img = "jem.jpg"
      name = "Jeremy North"
      position = "Donating time"
      social = [
        ["fa-twitter", "//twitter.com/jemnorth"],
        ["fa-home", "//datris.solutions"]
      ]
	  

	  
  # Client section
    [params.clients_list]
      enable = false

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      [[params.clients]]
        logo = "itsalocke.jpg"
        link = "//itsalocke.com"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"


  # Contact section
  [params.contact]
    enable = true
    title = "Get involved"
    subtitle  = "Want to donate your time or some funds to the event?"
    buttonText = "Send message"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.message]
      text = "How would you like to get involved? *"
      warning = "Please tell us how you want to help"


  # Footer section
  [params.footer]
    enable = true
    copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Battle of the Beards site & concept</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/stephlocke/battleofthebeards" property="cc:attributionName" rel="cc:attributionURL">Stephanie Locke</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br>Fork the site on <a href="//github.com/stephlocke/battleofthebeards" title="Battle of the Beards github repo">Github</a>'

  [[params.footer.social]]
    icon = "fa-twitter"
    link = "//twitter.com/battlingbeards"

  [[params.footer.social]]
    icon = "fa-facebook"
    link = "//facebook.com/battlingbeards"

  [[params.footer.quicklinks]]
    text = "Code of Conduct"
    link = "codeofconduct"

  [[params.footer.quicklinks]]
    text = "About BoB conf"
    link = "AboutEvents"
	
  [[params.footer.quicklinks]]
    link="https://bobconf.com"
    text="Registration"
